# Generated by Django 4.2.7 on 2023-12-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dys_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('publisher', models.CharField(max_length=255)),
                ('youtube_link', models.URLField()),
                ('school_level', models.CharField(choices=[('Primaire', 'Primaire'), ('College', 'college'), ('Lycee', 'lycee'), ('superieur', 'superieur')], max_length=20)),
            ],
        ),
    ]
