# Generated by Django 4.2.7 on 2023-12-21 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dys_app', '0003_completedlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='validated_by_users',
            field=models.ManyToManyField(blank=True, related_name='validated_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
