# Generated by Django 4.2.7 on 2023-12-21 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dys_app', '0005_remove_lesson_validated_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completed_lessons',
            field=models.ManyToManyField(through='dys_app.CompletedLesson', to=settings.AUTH_USER_MODEL),
        ),
    ]
