# Generated by Django 4.2.7 on 2023-12-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dys_app', '0006_lesson_completed_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='completed_lessons',
        ),
    ]
