# Generated by Django 4.2.7 on 2023-12-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dys_app', '0008_exercisetheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
            ],
        ),
    ]
